config/routes.rb
Parkstad::Application.routes.draw do

  get '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  
  resources :messages do
    resources :comments
  end
  
  resources :events do
    resources :attendances  
  end

  devise_for :users
  devise_for :admins

  get "pages/home"
  get "pages/contact"
  get "pages/charts"

  root 'pages#home'

end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :user
	validates :msg, presence: true
	has_many :comments
	accepts_nested_attributes_for :comments
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.order('created_at DESC').paginate(:page => params[:page], :per_page => 10)
    @message = Message.new
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @comments = @message.comments(@message)
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
    @message = current_user.messages.find(params[:id])
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    @message.user_name = current_user.name
    @message.user_id = current_user.id

    respond_to do |format|
      if @message.save
        format.html { redirect_to messages_path, notice: 'Message was successfully created.' }
        format.json { render action: 'show', status: :created, location: @message }
      else
        format.html { render action: 'new' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to messages_path, notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:msg, :user_name, :user_id)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= simple_form_for(@message) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :msg, label: false, placeholder: 'Plaats hier je bericht', as: :text %>
  </div>

  <div class="actions">
    <%= f.button :submit, 'Plaats!' %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<div id="container">
  <div id="primary" class="site-content">
    <div id="content" role="main">
      <article id="post-5" class="post-5 page type-page status-publish hentry">
        <header class="entry-header">
          <h1 class="entry-title">Berichten</h1>
        </header>
      </article>
     
      <div id="easybook">
        <% @messages.each do |message| %>
          <div class="easy_frame">
              <div class="easy_top_left">
                <strong class="easy_big" id="gbentry_74"><%= message.user_name %></strong>
                <strong class="easy_small"><%= message.created_at.to_s(:short) %></strong>
              </div>
              <div class="easy_top_right">
                <strong class="easy_small"><%= link_to "Reacties(#{message.comments.count}).", message_path(message) %></strong>
                <strong class="easy_small"><%= link_to 'Reageer op bericht.', [message, @comment]%></strong>
                <% if current_user.name == message.user_name %>
                  <strong class="easy_small"><%= link_to 'Pas text aan', edit_message_path(message) %></strong>
                  <strong class="easy_small"><%= link_to 'Verwijder Bericht', message, method: :delete, data: { confirm: 'Are you sure?' } %></strong>
                <% end %>
                  <% if admin_signed_in? %>
                    <strong class="easy_small"><%= link_to 'Verwijder Bericht', message, method: :delete, data: { confirm: 'Are you sure?' } %></strong>
                  <% end %>

              </div>
              <div style="clear: both;"></div>
            <div class="easy_content">
              <p><%= message.msg %></p>
              <% if admin_signed_in? %>
                <%= link_to 'Show', message %>
                <%= link_to 'Edit', edit_message_path(message) %>
                <%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
             </div>
          </div>
        <% end %>
      </div>

      <%= will_paginate @messages %>

      <h1>Nieuw Bericht</h1>

      <%= render 'messages/form' %>
    </div>
  </div>
</div>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>
<div id="container">
  <div id="primary" class="site-content">
    <div id="content" role="main">
      <article id="post-5" class="post-5 page type-page status-publish hentry">
        <header class="entry-header">
          <h1 class="entry-title">Berichten</h1>
        </header>
      </article>

			<div id="easybook">
			  <div class="easy_frame">
			      <div class="easy_top_left">
			        <strong class="easy_big" id="gbentry_74"><%= @message.user_name %></strong>
			        <strong class="easy_small"><%= @message.created_at.to_s(:short) %></strong>
			      </div>
			      <div class="easy_top_right">
			        <% if current_user.name == @message.user_name %>
			          <strong class="easy_small"><%= link_to 'Pas text aan', edit_message_path(@message) %></strong>
			        <% end %>
			      </div>
			      <div style="clear: both;"></div>
			    <div class="easy_content">
			      <p><%= @message.msg %></p>
			      <% if admin_signed_in? %>
			        <%= link_to 'Show', @message %>
			        <%= link_to 'Edit', edit_message_path(@message) %>
			        <%= link_to 'Destroy', @message, method: :delete, data: { confirm: 'Are you sure?' } %>
			      <% end %>
			     </div>
			  </div>
			</div>

			<% @comments.each do |comment| %>
			<div id="easybook">
			  <div class="easy_frame_comment">
			      <div class="easy_top_left">
			        <strong class="easy_big" id="gbentry_74"><%= comment.user_name %></strong>
			        <strong class="easy_small"><%= comment.created_at.to_s(:short) %></strong>
			      </div>
			      <div class="easy_top_right">
			        <% if current_user.name == comment.user_name %>
			        	<strong class="easy_small"><%= link_to 'Verwijder Bericht', [@message, comment], method: :delete, data: { confirm: 'Are you sure?' } %></strong>
			          <strong class="easy_small"><%= link_to 'Pas text aan', edit_message_comment_path(@message, comment) %></strong>
			        <% end %>
			        <% if admin_signed_in? %>
			        <strong class="easy_small"><%= link_to 'Verwijder Bericht', [@message, comment], method: :delete, data: { confirm: 'Are you sure?' } %></strong>
			        <% end %>
			      </div>
			      <div style="clear: both;"></div>
			    <div class="easy_content">
			      <p><%= comment.comment %></p>
			      <% if admin_signed_in? %>
			        <%= link_to 'Show', comment %>
			        <%= link_to 'Edit', edit_message_comment_path(@message, comment) %>
			        <%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
			      <% end %>
			    </div>
			  </div>
			</div>
			<% end %>

			<%= link_to 'Plaats reactie', new_message_comment_path(@message) %>
 		</div>
	</div>
</div>