config/routes.rb
Parkstad::Application.routes.draw do

  get '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  
  resources :messages do
    resources :comments
  end
  
  resources :events do
    resources :attendances  
  end

  devise_for :users
  devise_for :admins

  get "pages/home"
  get "pages/contact"
  get "pages/charts"

  root 'pages#home'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :message
	belongs_to :users
	validates :comment, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :get_message
  before_filter :authenticate_user!
  # GET /comments
  # GET /comments.json
  def index
    @comments = @message.comments
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @message = Message.find(params[:message_id])
    @comment = @message.comments.find(params[:id])
  end

  # GET /comments/new
  def new
    @message = Message.find(params[:message_id])
    @comment = @message.comments.build
  end

  # GET /comments/1/edit
  def edit
    @message = Message.find(params[:message_id])
    @comment = @message.comments.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = @message.comments.build(comment_params)
    @comment.user_name = current_user.name
    @comment.user_id = current_user.id

    respond_to do |format|
      if @comment.save
        format.html { redirect_to message_path(@message), notice: 'Message was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    @comment = @message.comments.find(params[:id])

    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to message_path(@message), notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = @message.comments.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to message_path(@message) }
      format.json { head :no_content }
    end
  end

  private

    def get_message
      @message = Message.find(params[:message_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:comment, :user_name, :user_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= simple_form_for [@message, @comment] do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :comment, label: '', placeholder: 'Plaats hier je bericht', as: :text %>
  </div>

  <div class="actions">
    <%= f.button :submit, 'Plaats!' %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Back', message_path(@message) %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th>User name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.comment %></td>
        <td><%= comment.user_name %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_message_comment_path %>

app/views/comments/new.html.erb
<h1>Nieuw commentaar</h1>

<%= render 'form' %>

<%= link_to 'Back', message_comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @comment.comment %>
</p>

<p>
  <strong>User name:</strong>
  <%= @comment.user_name %>
</p>