config/routes.rb
Parkstad::Application.routes.draw do

  get '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  
  resources :messages do
    resources :comments
  end
  
  resources :events do
    resources :attendances  
  end

  devise_for :users
  devise_for :admins

  get "pages/home"
  get "pages/contact"
  get "pages/charts"

  root 'pages#home'

end

app/views/pages/charts.html.erb
<div id="container" style="width:100%; height:400px;">

<script>
$(function () {
    $('#container').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: 'Times signed in'
        },
        subtitle: {
            text: 'Parkstad 3'
        },
        xAxis: {
            categories: [
                'Januari',
                'Februari',
                'Maart',
                'April',
                'Mei',
                'Juni',
                'July',
                'Augustus',
                'September',
                'October',
                'November',
                'December'
            ]
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Aantal keer ingelogd'
            }
        },
        tooltip: {
            headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
            pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                '<td style="padding:0"><b>{point.y:.1f} mm</b></td></tr>',
            footerFormat: '</table>',
            shared: true,
            useHTML: true
        },
        plotOptions: {
            column: {
                pointPadding: 0.2,
                borderWidth: 0
            }
        },

        series: [{
            name: 'Voetbal',
            data: [49.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]

        }, {
            name: 'Poes',
            data: [83.6, 78.8, 98.5, 93.4, 106.0, 84.5, 105.0, 104.3, 91.2, 83.5, 106.6, 92.3]

        }, {
            name: 'Vrouw',
            data: [48.9, 38.8, 39.3, 41.4, 47.0, 48.3, 59.0, 59.6, 52.4, 65.2, 59.3, 51.2]

        }, {
            name: 'Game',
            data: [42.4, 33.2, 34.5, 39.7, 52.6, 75.5, 57.4, 60.4, 47.6, 39.1, 46.8, 51.1]

        }]
    });
});
</script>
</div>

app/views/pages/contact.html.erb
<div id="contact">
  <div class="row map">
    <div class="container">
        <div class="span5 box_wrapp">
            <div class="box_cont">
                <div class="head">
                    <h6>Contactgegevens: </h6>
                </div>
                <ul class="street">
                    <ul class="street">
                    <li>Parkstad</li>
                    <l1>Sportpark de Eendracht</li>
                    <li>Adres: Bok de Korverweg 16</li>
                    <li>Postcode: 1067 HR Amsterdam</li>
                    <li>020-6114400</li>
                </ul>
            </div>
        </div>
    </div>
     <iframe width="100%" height="600" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.nl/maps?ie=UTF8&amp;q=S.V.+Parkstad&amp;fb=1&amp;gl=nl&amp;hq=parkstad&amp;hnear=0x47c63fb5949a7755:0x6600fd4cb7c0af8d,Amsterdam&amp;cid=0,0,1047287636828630532&amp;t=m&amp;z=16&amp;iwloc=A&amp;output=embed"></iframe><br /><small><a href="http://maps.google.nl/maps?ie=UTF8&amp;q=S.V.+Parkstad&amp;fb=1&amp;gl=nl&amp;hq=parkstad&amp;hnear=0x47c63fb5949a7755:0x6600fd4cb7c0af8d,Amsterdam&amp;cid=0,0,1047287636828630532&amp;t=m&amp;z=16&amp;iwloc=A&amp;source=embed" style="color:#0000FF;text-align:left">Grotere kaart weergeven</a></small>
  </div>
</div>

app/views/pages/home.html.erb
<% if user_signed_in? %> 
  <div id="primary" class="site-content">
    <div id="content" role="main">
      <article id="post-5" class="post-5 page type-page status-publish hentry">
        <header class="entry-header">
          <h1 class="entry-title">Eerstvolgende training/wedstrijd</h1>
        </header>
      </article>

      <div id="volgende">
        <h1> Datum </h1>
        <p><%= @event.start_at.strftime("%b %d, %Y")%></p>
        <p><%= @event.name.upcase %></p>

        <h1>Totaal aanwezig:</h1>
          <p><%= @there_count %> man</p>

        <h1>Aanwezig zijn:</h1>
          <% @there.each do |x| %>
          <p><%= x.user.name %></p>
          <% end %><br>
          <% unless @event.start_at.to_s(:short).to_date == Date.today %>
            <p><%= link_to 'Geef direct je aanwezigheid door', event_path(@event) %></p>
          <% else %>
            <p>Het doorgeven of wijzigen van je aanwezigheid op de speeldag is niet mogelijk.</p>
          <% end %>
      </div><br>

    <header class="entry-header">    
      <h1 class="entry-title">Laatste berichten</h1>
    </header>
    <div id="easybook">
      <% @messages.each do |message| %>
        <p class="clr"></p>
        <div class="easy_frame">
          <div class="easy_top">
            <div class="easy_top_left">
              <strong class="easy_big" id="gbentry_74"><%= message.user_name %></strong>
              <strong class="easy_small"><%= message.created_at.to_s(:short) %></strong>
            </div>
            <div class="easy_top_right">
              <% if current_user.name == message.user_name %>
             <strong class="easy_small"><%= link_to 'Pas text aan', edit_message_path(message) %></strong>
              <% end %>
             <strong class="easy_small"><%= link_to 'Ga naar bericht', message_path(message) %></strong>
            </div>
            </div>
            <div style="clear: both;"></div>
          </div>
          <div class="easy_content">
            <p><%= message.msg %></p>
            <% if admin_signed_in? %>
              <%= link_to 'Show', message %>
              <%= link_to 'Edit', edit_message_path(message) %>
              <%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="center hero-unit">
      <h1>Welkom op de website van Parkstad 3</h1>
      <p> Deze website is geheel voor en door spelers van Parkstad.</p><br>

      <p><%= link_to 'Al aangemeld ? Log dan hier in.',  new_user_session_path , class: "btn btn-large btn-primary" %></p><br>

      <p><%= link_to 'Nog niet aangemeld ? Meld je nu aan!',  new_user_registration_path , class: "btn btn-small-btn-primary" %></p>
  </div>
<% end %>