config/routes.rb
Parkstad::Application.routes.draw do

  get '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  
  resources :messages do
    resources :comments
  end
  
  resources :events do
    resources :attendances  
  end

  devise_for :users
  devise_for :admins

  get "pages/home"
  get "pages/contact"
  get "pages/charts"

  root 'pages#home'

end

app/views/layouts/_footer.html.erb
<div class="footer">
  <small>
    <p>&copy; Gemaakt door: Peter van den Berg</p>
  </small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/">Parkstad 3</a>
      <div class="container nav-collapse">
        <ul class="nav">
          <% if user_signed_in? %> 
            <li><%= link_to "Kalender", calendar_path, method: :get  %></li> 
            <li><%= link_to "Berichten", messages_path  %></li>
          <% elsif admin_signed_in? %>
            <li><%= link_to "Kalender", calendar_path  %></li>
            <li><%= link_to "Berichten", messages_path  %></li>
          <% end %>
            <li><%= link_to "Contact", pages_contact_path  %></li>
        </ul>

       <ul class="nav pull-right">
            <% if admin_signed_in? %>
              <li><%= link_to "AdminLogout", destroy_admin_session_path, method: :delete %></li>
            <% elsif user_signed_in? %>
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign up", new_user_registration_path , id: "signup" %></li>
              <li><%= link_to 'Log-in', '#', id: "loginUrl", method: :get %></li>
              
              <div class ='loginform'>
                <%= simple_form_for(User.new, :url => '/users/sign_in/') do |f| %>
                  <div class="form-inputs">
                    <%= f.input :email, :autofocus => true, label: false, placeholder: "Email", input_html: { id: 'navbar_email'} %>
                    <%= f.input :password, label: false, placeholder: "Wachtwoord", input_html: { id: 'navbar_password'} %>
                  </div>

                  <div class="form-actions">
                    <%= f.button :submit, "Sign in" %>
                  </div>
                <% end %>
              </div>

            <% end %>
        </ul>  
        </div><!--/.nav-collapse -->
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/_homepagebanner.html.erb
<% if user_signed_in? %> 
  <!-- start banner -->
  <div id="main" class="wrapper"><div id="slider" class="flexslider">
      
  <div class="flex-viewport" style="overflow: hidden; position: relative;"><ul class="slides" style="width: 1200%; -webkit-transition: 0.6s; transition: 0.6s; -webkit-transform: translate3d(-2826px, 0, 0);">
      <li class="clone" style="width: 1413px; float: left; display: block;">
        <a href=""><img src="/assets/slide12.jpg" alt=""></a>
        <div class="flex-holder">
          <div class="flex-caption">
            <div>
              <h1 style="background: #43bd3d;"><a href="" style="color: #fff;">Welkom op de website</a></h1><br>
              <h1 style="background: #43bd3d;"><a href="" style="color: #fff;">van Parkstad 3</a></h1>
            </div>
          </div>
        </div>
      </li>
      <li style="width: 1413px; float: left; display: block;" class="">
        <a href="http://chaletbouquetins.nl/chalet/"><img src="/assets/slide2.jpg" alt=""></a>
        <div class="flex-holder">
          <div class="flex-caption">
            <div>
              <h1 style="background: #428cbc;"><a href="" style="color: #fff;">Vorig jaar kampioen</a></h1><br>
              <h1 style="background: #428cbc;"><a href="" style="color: #fff;">Dit jaar weer</a></h1>
            </div>
          </div>
        </div>
      </li>
      <li class="flex-active-slide" style="width: 1413px; float: left; display: block;">
        <a href="http://chaletbouquetins.nl/chalet/"><img src="/assets/slide3.jpg" alt=""></a>
        <div class="flex-holder">
          <div class="flex-caption">
            <div>
              <h1 style="background: #d96f4e;"><a href="/messages/" style="color: #fff;">Klik hier</a></h1><br>
              <h1 style="background: #d96f4e;"><a href="/messages/" style="color: #fff;">voor de laatste berichten</a></h1>
            </div>
          </div>
        </div>
      </li>
      <li class="" style="width: 1413px; float: left; display: block;">
        <a href="http://chaletbouquetins.nl/crans-montana/"><img src="assets/slide4.jpg" alt="Ski"></a>
        <div class="flex-holder">
          <div class="flex-caption">
            <div>
                <h1 style="background: #428cbc;"><a href="/calendar/" style="color: #fff;">Klik hier</a></h1><br>
                <h1 style="background: #428cbc;"><a href="/calendar/" style="color: #fff;">voor het programma</a></h1>
            </div>
          </div>
        </div>
      </li>

    </div>
    <ul class="flex-direction-nav">
      <li><a class="flex-prev" href="#">Previous</a></li>
      <li><a class="flex-next" href="#">Next</a></li> </ul>
  </div> <!-- End of banner -->

  <!-- start slider -->
  <div class="carouselWrapper">
    <div class="site-content">
      <div id="carousel" class="flexsliders">
        <div class="flex-viewport" style="overflow: hidden; position: relative;">
          <ul class="slides" style="width: 800%; -webkit-transition: 0s; transition: 0s; -webkit-transform: translate3d(0px, 0, 0);">
            <li class="" style="width: 215px; float: left; display: block;"><img src="/assets/slide12_thumb.jpg" alt="Exclusief chalet"></li>
            <li class="flex-active-slide" style="width: 215px; float: left; display: block;"><img src="/assets/slide2_thumb.jpg" alt="Chalet"></li>
            <li class="" style="width: 215px; float: left; display: block;"><img src="/assets/slide3_thumb.jpg" alt="Ski"></li>
            <li style="width: 215px; float: left; display: block;" class=""><img src="/assets/slide4_thumb.jpg" alt="Golf "></li>
          </ul>
        </div>
        <ul class="flex-direction-nav">
          <li><a class="flex-prev flex-disabled" href="#">Previous</a></li>
          <li><a class="flex-next flex-disabled" href="#">Next</a></li>
        </ul>
      </div>
    </div>
  </div>
  <!-- end of slider -->

  <script type="text/javascript">
  jQuery(window).load(function() {
      jQuery('#carousel').flexslider({
          animation: "slide",
          controlNav: false,
          animationLoop: false,
          slideshow: false,
          itemWidth: 215,
          itemMargin: 20,
          asNavFor: '#slider'
      });
      jQuery('#slider').flexslider({
          animation: "slide",
          controlNav: false,
          animationLoop: true,
          slideshow: true,
          slideshowSpeed: 4500,
          sync: "#carousel",
          start: function(slider){
              jQuery('body').removeClass('loading');
          }
      });
  });
  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Parkstad" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= stylesheet_link_tag "event_calendar" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "event_calendar" %>
    <%= javascript_include_tag "highcharts.js" %>
  </head>
  <body>

    <%= render 'layouts/header' %>

    <% if current_page?(root_path) %>
      <%= render 'layouts/homepagebanner' %>
    <% end %>

    <div class="container">
        <%= bootstrap_flash %>
        <div class="row"><br><br><br>
            <%= yield %>
        </div><!--/row-->

        <%= render "layouts/footer" %>

    </div> <!-- /container -->

  </body>
</html>